### ISSUE TITLE
Problems with ESPRESSO - calc-sims.py

### ISSUE THREAD

**Issue by Lambru99** [notem/ESPRESSO-Flow-Correlation#1]
I'm trying to run ESPRESSO but when it finishes to exec the part of code related to train and test and start to run calc-sims.py, I receive this error:
```bash
=> Calculating sims...
./auto.sh: line 141: 44588 Killed                  python src/calc-sims.py --exp_config $EXP_CONFIG --dists_file $DISTS_FILE --ckpt $CKPT_DIR/$TRAINED_NET/$CKPT_NAME
Traceback (most recent call last):
  File "/storage/disk0/espresso/ESPRESSO-Flow-Correlation/src/benchmark-mlp.py", line 119, in <module>
    with open(args.dists_file, 'rb') as fi:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './exps/espresso_online/sims/margin_100.pkl'
Traceback (most recent call last):
  File "/storage/disk0/espresso/ESPRESSO-Flow-Correlation/src/benchmark-thr.py", line 164, in <module>
    with open(args.dists_file, 'rb') as fi:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './exps/espresso_online/sims/margin_100.pkl'
(pytorch) ...espresso/ESPRESSO-Flow-Correlation$ ./auto.sh 
```
For starting the process, I simply run `auto.sh`. 
I think that I correctly put the dataset in the folder, anyway my directory tree of the project are:

```bash
├── Pipfile
├── README.md
├── auto.sh
├── configs
│   ├── exps
│   │   ├── august.json
│   │   ├── july.json
│   │   ├── june.json
│   │   ├── obfs4.json
│   │   ├── ts-august.json
│   │   └── ts-june.json
│   └── nets
│       ├── dcf.json
│       ├── espresso-tweaks.json
│       ├── espresso.json
│       ├── greentea.json
│       ├── hotwater.json
│       └── laserbeak.json
├── data
│   ├── README.md
│   ├── dcf-august.pkl
│   ├── dcf-july.pkl
│   ├── dcf-june.pkl
│   ├── dcf-obfs4.pkl
│   └── ts-sim.py
├── exps
│   └── espresso_online
│       ├── ckpts
│       │   └── margin_100
│       │       └── final.pth
│       ├── log
│       │   └── margin_100.txt
│       ├── mlp
│       │   └── margin_100
│       ├── sims
│       └── thr
│           └── margin_100
├── result-imgs
│   ├── arch-roc.png
│   ├── dcf-roc.png
│   ├── espresso-roc.png
│   ├── multi-roc.png
│   └── ts-roc.png
└── src
    ├── benchmark-mlp.py
    ├── benchmark-thr.py
    ├── calc-sims.py
    ├── train.py
    └── utils
        ├── __pycache__
        │   ├── data.cpython-312.pyc
        │   ├── layers.cpython-312.pyc
        │   ├── loss.cpython-312.pyc
        │   └── processor.cpython-312.pyc
        ├── data.py
        ├── layers.py
        ├── loss.py
        ├── nets
        │   ├── __pycache__
        │   │   ├── dcfnet.cpython-312.pyc
        │   │   ├── espressonet.cpython-312.pyc
        │   │   └── transdfnet.cpython-312.pyc
        │   ├── dcfnet.py
        │   ├── espressonet.py
        │   └── transdfnet.py
        └── processor.py
```
How can I solve the problem?

**Comment by notem** [comment]
The first line in your log indicates that your OS is killing the process, most likely due to memory exhaustion. 
The later sections of the script fail because the expected files (e.g., matrix of similarities) were not generated. 

If the training runs correctly and it's failing during the calc_sims.py script, then its probably running out of memory when building the similarity matrix for the testing samples.  You can reduce the number of testing samples used in the configs/exps/ file, or you can rewrite the function to use batching (much more effort). Memory cost scaling is quadratic to the number of samples when calculating pairwise similarity in the current code.

**Comment by Lambru99** [comment]
thank you, I modified this file:
```bash
├── configs
│   ├── exps
│   │   ├── june.json
```
and I decrease the number in the te_range, and now it works
